### ISSUE TITLE
Staked MIM not displaying, hMIM gauge token unavailable

### ISSUE THREAD

**Issue by heyJonBray** [hundred-finance/hundred-interface#39]
Yesterday I withdrew MIM I had in the lending pool to stake, earn HND and take part in the broader ecosystem on Fantom.

[Fantom Opera Tx: 0x0c7bc79be28a8e1b0fd01b128493c4961a8f1c25832cdadc61a4ff83251e6e02](https://ftmscan.com/tx/0x0c7bc79be28a8e1b0fd01b128493c4961a8f1c25832cdadc61a4ff83251e6e02)

Immediately after the deposit was complete, my staked balance showed on the main Hundred Finance UI—I closed my laptop and called it a night.

Today I went to start exploring the gauge system but to my surprise I had no staked assets at all. Furthermore, I could find no UI options or fields that even indicated that I had **ANY** funds deposited to Hundred Finance.

After not finding help in the docs, frustrated, I just wanted to get my `$MIM` back and move to another protocol, however even direct contract interaction with the `withdrawFromGaugeToUnderlying` method, as well as withdrawing from gauge to hTokens threw an error stating failure was expected, no luck there.

I've read through the documentation, I haven't taken out any borrowed assets that would have caused a liquidation situation, I've staked tokens on Hundred before and always had them show up correctly and been able to interact with my deposits.

**Can someone explain what type of limbo my MIM and gauge tokens are currently stuck in?**

_I'm very familiar with Curve (which the Hundred gauge systems seems to be an implementation of), but I'm at a loss as to what I can currently do in the ecosystem and how I can ensure my funds are safe._

Cheers,
HJB

**Comment by SHA-2048** [comment]
Hi,

We migrated fantom to mveHND this morning. To access your positions go to old.hundred.finance
Also join the project discord to keep track of these anouncements

you will have to unstake from old deploy and stake into the new one, as rewards will be distributed only on new deploy starting next epoch
